;-----------------------------------------------------------------------
; M5Stamp-S3Bat CameraWebServer
; Porting of espressif/arduino-esp32 example to M5Stamp-S3Bat.
; See also https://github.com/espressif/arduino-esp32/tree/master/libraries/ESP32/examples/Camera/CameraWebServer
;-----------------------------------------------------------------------
[env]
platform = espressif32@7.1.1
framework = arduino

board_build.flash_mode = qio
board_build.f_flash = 80000000L

lib_deps = https://github.com/GOB52/gob_GC0308.git @ ^0.1.0
lib_ldf_mode = deep

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 1500000

build_flags = -Wall -Wextra -Wreturn-local-addr -Werror=format -Werror=return-local-addr
  -DBOARD_HAS_PSRAM -mfix-esp32-psram-cache-issue
  -Wl,--wrap=xTaskCreatePinnedToCore

extra_scripts = pre:./html/generate_html_cpp.py
  post:./merge_bin.py

; --------------------------------
; Choose build options
[option_release]
build_flags =  -DCORE_DEBUG_LEVEL=3
 -DLOG_LOCAL_LEVEL=3
 -DAPP_LOG_LEVEL=3

; Enable face detection/recognition
[env:M5StampS3Bat]
board = m5stack-stamps3
board_build.arduino.memory_type = qio_opi
upload_speed = 1500000
build_type=release
build_flags=${env.build_flags} ${option_release.build_flags} -DCWS_ENABLE_FACE
board_build.partitions = for_face.csv
